// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/68d35d479f9482c849239dbb
###
GET http://localhost:8080/contacts/68d35d479f9482c849239dbc
###
GET http://localhost:8080/contacts/68d35d479f9482c849239dbd

// PRODUCTION Deploy
###
GET https://lesson-2-gamu.onrender.com/contacts
###
GET https://lesson-2-gamu.onrender.com/contacts/68d35d479f9482c849239dbb
###
GET https://lesson-2-gamu.onrender.com/contacts/68d35d479f9482c849239dbc
###
GET https://lesson-2-gamu.onrender.com/contacts/68d35d479f9482c849239dbd


### Create a new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Smith",
  "email": "alice@example.com",
  "favoriteColor": "Blue",
  "birthday": "1990-01-01"
}

### Update an existing contact
PUT http://localhost:8080/contacts/68dfda4c1136fa83ea42f4b9
Content-Type: application/json

{
  "firstName": "Alice",
  "favoriteColor": "Green"
}


###
GET http://localhost:8080/contacts/68dfda4c1136fa83ea42f4b9


### Delete a contact
DELETE http://localhost:8080/contacts/68dfda4c1136fa83ea42f4b9


###
GET https://lesson-2-gamu.onrender.com/contacts